### ISSUE TITLE
Training Corpus release?

### ISSUE THREAD

**Issue by imr555** [csebuetnlp/banglabert#5]
Will the training corpus be released?

Thanks in advance.

**Comment by Tahmid04** [comment]
Hi, the pretraining corpus is now available upon request! Please see [here](https://github.com/csebuetnlp/banglabert/blob/master/README.md#datasets).

**Comment by imr555** [comment]
> Hi, the pretraining corpus is now available upon request! Please see [here](https://github.com/csebuetnlp/banglabert/blob/master/README.md#datasets).

Thank You Very Much for the detailed reply and the link to the dataset request procedure.
